version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/infrastructure-as-types

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: sbt -batch update

      - run: sbt -batch +test:compile

      - run: sbt -batch +test
