version: 2.1
jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-1604:201903-01

    working_directory: ~/infrastructure-as-types

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # -batch is necessary to make sure sbt doesn't stall waiting for user input in case of certain failures
      - run: echo '-batch' >> .sbtopts
      - run: sbt update
      - run: sbt +scalafmtCheckAll
      - run: sbt +compile
      - run: sbt +test:compile
      - run: sbt +test

      - run:
          name: 'Install kind & kubectl'
          command: |
            set -x
            curl -fLo ./kind "https://kind.sigs.k8s.io/dl/v0.8.1/kind-Linux-amd64"
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
            curl -fLo ./kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: Create cluster
          command: |
            kind create cluster
            mkdir -p ~/.kube/
            kind get kubeconfig | tee ~/.kube/config

      - run:
          name: Deploy GuestBook
          environment:
            IAT_KUBE_CONTEXT: kind-kind
          no_output_timeout: 1m
          command: |
            sbt "project iat-examples" "runMain com.virtuslab.iat.examples.GuestBook"
      - run:
          name: Wait for GuestBook pods to spin up
          command: |
            kubectl wait --namespace guestbook --for condition=ready --selector 'app in (guestbook,redis)' --timeout 5m pods
      - run:
          name: '[Background] Launch port forwarding for GuestBook frontend'
          background: true
          command: kubectl port-forward --namespace=guestbook service/frontend 3000:80
      - run:
          name: Smoke-test the deployed GuestBook
          command: |
            until nc -z localhost 3000; do
              echo 'Waiting for port forwarding to activate...'
              sleep 500
            done

            set -x
            curl 'http://localhost:3000/guestbook.php?cmd=set&key=messages&value=1,2,3,4'
            result=$(curl 'http://localhost:3000/guestbook.php?cmd=get&key=messages' | jq -r '.data')
            [[ $result == "1,2,3,4" ]]
      - run:
          # Technically not needed since the VM will be wiped out at the end anyway.
          name: Delete cluster
          when: always
          command: kind delete cluster
