/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object LogsApi {

  def apply(baseUrl: String = "http://localhost")(implicit serializer: SttpSerializer) = new LogsApi(baseUrl)
}

class LogsApi(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * Expected answers:
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param logpath path to the log
   */
  def logFileHandler(logpath: String)(implicit apiKey: ApiKeyValue): ApiRequestT[Unit] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/logs/${logpath}")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def logFileListHandler()(implicit apiKey: ApiKeyValue): ApiRequestT[Unit] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/logs/")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[Unit])

}

