/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.APIResourceList
import org.openapitools.client.model.CSIDriver
import org.openapitools.client.model.CSIDriverList
import org.openapitools.client.model.CSINode
import org.openapitools.client.model.CSINodeList
import org.openapitools.client.model.DeleteOptions
import org.openapitools.client.model.Status
import org.openapitools.client.model.StorageClass
import org.openapitools.client.model.StorageClassList
import org.openapitools.client.model.VolumeAttachment
import org.openapitools.client.model.VolumeAttachmentList
import org.openapitools.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object StorageV1beta1Api {

  def apply(baseUrl: String = "http://localhost")(implicit serializer: SttpSerializer) = new StorageV1beta1Api(baseUrl)
}

class StorageV1beta1Api(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * create a CSIDriver
   * 
   * Expected answers:
   *   code 200 : CSIDriver (OK)
   *   code 201 : CSIDriver (Created)
   *   code 202 : CSIDriver (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def createCSIDriver(pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: CSIDriver)(implicit apiKey: ApiKeyValue): ApiRequestT[CSIDriver] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSIDriver])

  /**
   * create a CSINode
   * 
   * Expected answers:
   *   code 200 : CSINode (OK)
   *   code 201 : CSINode (Created)
   *   code 202 : CSINode (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def createCSINode(pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: CSINode)(implicit apiKey: ApiKeyValue): ApiRequestT[CSINode] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSINode])

  /**
   * create a StorageClass
   * 
   * Expected answers:
   *   code 200 : StorageClass (OK)
   *   code 201 : StorageClass (Created)
   *   code 202 : StorageClass (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def createStorageClass(pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: StorageClass)(implicit apiKey: ApiKeyValue): ApiRequestT[StorageClass] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[StorageClass])

  /**
   * create a VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : VolumeAttachment (OK)
   *   code 201 : VolumeAttachment (Created)
   *   code 202 : VolumeAttachment (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def createVolumeAttachment(pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: VolumeAttachment)(implicit apiKey: ApiKeyValue): ApiRequestT[VolumeAttachment] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[VolumeAttachment])

  /**
   * delete a CSIDriver
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 202 : Status (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSIDriver
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param body 
   */
  def deleteCSIDriver(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, gracePeriodSeconds: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers/${name}?pretty=$pretty&dryRun=$dryRun&gracePeriodSeconds=$gracePeriodSeconds&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete a CSINode
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 202 : Status (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSINode
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param body 
   */
  def deleteCSINode(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, gracePeriodSeconds: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes/${name}?pretty=$pretty&dryRun=$dryRun&gracePeriodSeconds=$gracePeriodSeconds&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete collection of CSIDriver
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   * @param body 
   */
  def deleteCollectionCSIDriver(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, dryRun: Option[String] = None, fieldSelector: Option[String] = None, gracePeriodSeconds: Option[Int] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&dryRun=$dryRun&fieldSelector=$fieldSelector&gracePeriodSeconds=$gracePeriodSeconds&labelSelector=$labelSelector&limit=$limit&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete collection of CSINode
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   * @param body 
   */
  def deleteCollectionCSINode(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, dryRun: Option[String] = None, fieldSelector: Option[String] = None, gracePeriodSeconds: Option[Int] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&dryRun=$dryRun&fieldSelector=$fieldSelector&gracePeriodSeconds=$gracePeriodSeconds&labelSelector=$labelSelector&limit=$limit&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete collection of StorageClass
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   * @param body 
   */
  def deleteCollectionStorageClass(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, dryRun: Option[String] = None, fieldSelector: Option[String] = None, gracePeriodSeconds: Option[Int] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&dryRun=$dryRun&fieldSelector=$fieldSelector&gracePeriodSeconds=$gracePeriodSeconds&labelSelector=$labelSelector&limit=$limit&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete collection of VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   * @param body 
   */
  def deleteCollectionVolumeAttachment(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, dryRun: Option[String] = None, fieldSelector: Option[String] = None, gracePeriodSeconds: Option[Int] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&dryRun=$dryRun&fieldSelector=$fieldSelector&gracePeriodSeconds=$gracePeriodSeconds&labelSelector=$labelSelector&limit=$limit&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete a StorageClass
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 202 : Status (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param body 
   */
  def deleteStorageClass(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, gracePeriodSeconds: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses/${name}?pretty=$pretty&dryRun=$dryRun&gracePeriodSeconds=$gracePeriodSeconds&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * delete a VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : Status (OK)
   *   code 202 : Status (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the VolumeAttachment
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \"orphan\" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
   * @param body 
   */
  def deleteVolumeAttachment(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, gracePeriodSeconds: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None, body: Option[DeleteOptions] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[Status] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments/${name}?pretty=$pretty&dryRun=$dryRun&gracePeriodSeconds=$gracePeriodSeconds&orphanDependents=$orphanDependents&propagationPolicy=$propagationPolicy")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[Status])

  /**
   * get available resources
   * 
   * Expected answers:
   *   code 200 : APIResourceList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def getAPIResources()(implicit apiKey: ApiKeyValue): ApiRequestT[APIResourceList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[APIResourceList])

  /**
   * list or watch objects of kind CSIDriver
   * 
   * Expected answers:
   *   code 200 : CSIDriverList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def listCSIDriver(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[CSIDriverList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&fieldSelector=$fieldSelector&labelSelector=$labelSelector&limit=$limit&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[CSIDriverList])

  /**
   * list or watch objects of kind CSINode
   * 
   * Expected answers:
   *   code 200 : CSINodeList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def listCSINode(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[CSINodeList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&fieldSelector=$fieldSelector&labelSelector=$labelSelector&limit=$limit&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[CSINodeList])

  /**
   * list or watch objects of kind StorageClass
   * 
   * Expected answers:
   *   code 200 : StorageClassList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def listStorageClass(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[StorageClassList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&fieldSelector=$fieldSelector&labelSelector=$labelSelector&limit=$limit&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[StorageClassList])

  /**
   * list or watch objects of kind VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : VolumeAttachmentList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If 'true', then the output is pretty printed.
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def listVolumeAttachment(pretty: Option[String] = None, allowWatchBookmarks: Option[Boolean] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[VolumeAttachmentList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments?pretty=$pretty&allowWatchBookmarks=$allowWatchBookmarks&continue=$continue&fieldSelector=$fieldSelector&labelSelector=$labelSelector&limit=$limit&resourceVersion=$resourceVersion&timeoutSeconds=$timeoutSeconds&watch=$watch")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[VolumeAttachmentList])

  /**
   * partially update the specified CSIDriver
   * 
   * Expected answers:
   *   code 200 : CSIDriver (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSIDriver
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint. This field is required for apply requests (application/apply-patch) but optional for non-apply patch types (JsonPatch, MergePatch, StrategicMergePatch).
   * @param force Force is going to \"force\" Apply requests. It means user will re-acquire conflicting fields owned by other people. Force flag must be unset for non-apply patch requests.
   * @param body 
   */
  def patchCSIDriver(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, force: Option[Boolean] = None, body: String)(implicit apiKey: ApiKeyValue): ApiRequestT[CSIDriver] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager&force=$force")
      .contentType("application/json-patch+json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSIDriver])

  /**
   * partially update the specified CSINode
   * 
   * Expected answers:
   *   code 200 : CSINode (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSINode
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint. This field is required for apply requests (application/apply-patch) but optional for non-apply patch types (JsonPatch, MergePatch, StrategicMergePatch).
   * @param force Force is going to \"force\" Apply requests. It means user will re-acquire conflicting fields owned by other people. Force flag must be unset for non-apply patch requests.
   * @param body 
   */
  def patchCSINode(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, force: Option[Boolean] = None, body: String)(implicit apiKey: ApiKeyValue): ApiRequestT[CSINode] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager&force=$force")
      .contentType("application/json-patch+json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSINode])

  /**
   * partially update the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : StorageClass (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint. This field is required for apply requests (application/apply-patch) but optional for non-apply patch types (JsonPatch, MergePatch, StrategicMergePatch).
   * @param force Force is going to \"force\" Apply requests. It means user will re-acquire conflicting fields owned by other people. Force flag must be unset for non-apply patch requests.
   * @param body 
   */
  def patchStorageClass(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, force: Option[Boolean] = None, body: String)(implicit apiKey: ApiKeyValue): ApiRequestT[StorageClass] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager&force=$force")
      .contentType("application/json-patch+json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[StorageClass])

  /**
   * partially update the specified VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : VolumeAttachment (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the VolumeAttachment
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint. This field is required for apply requests (application/apply-patch) but optional for non-apply patch types (JsonPatch, MergePatch, StrategicMergePatch).
   * @param force Force is going to \"force\" Apply requests. It means user will re-acquire conflicting fields owned by other people. Force flag must be unset for non-apply patch requests.
   * @param body 
   */
  def patchVolumeAttachment(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, force: Option[Boolean] = None, body: String)(implicit apiKey: ApiKeyValue): ApiRequestT[VolumeAttachment] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager&force=$force")
      .contentType("application/json-patch+json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[VolumeAttachment])

  /**
   * read the specified CSIDriver
   * 
   * Expected answers:
   *   code 200 : CSIDriver (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSIDriver
   * @param pretty If 'true', then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'. Deprecated. Planned for removal in 1.18.
   * @param export Should this value be exported.  Export strips fields that a user can not specify. Deprecated. Planned for removal in 1.18.
   */
  def readCSIDriver(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[CSIDriver] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers/${name}?pretty=$pretty&exact=$exact&export=$export")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[CSIDriver])

  /**
   * read the specified CSINode
   * 
   * Expected answers:
   *   code 200 : CSINode (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSINode
   * @param pretty If 'true', then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'. Deprecated. Planned for removal in 1.18.
   * @param export Should this value be exported.  Export strips fields that a user can not specify. Deprecated. Planned for removal in 1.18.
   */
  def readCSINode(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[CSINode] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes/${name}?pretty=$pretty&exact=$exact&export=$export")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[CSINode])

  /**
   * read the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : StorageClass (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param pretty If 'true', then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'. Deprecated. Planned for removal in 1.18.
   * @param export Should this value be exported.  Export strips fields that a user can not specify. Deprecated. Planned for removal in 1.18.
   */
  def readStorageClass(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[StorageClass] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses/${name}?pretty=$pretty&exact=$exact&export=$export")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[StorageClass])

  /**
   * read the specified VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : VolumeAttachment (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the VolumeAttachment
   * @param pretty If 'true', then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'. Deprecated. Planned for removal in 1.18.
   * @param export Should this value be exported.  Export strips fields that a user can not specify. Deprecated. Planned for removal in 1.18.
   */
  def readVolumeAttachment(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequestT[VolumeAttachment] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments/${name}?pretty=$pretty&exact=$exact&export=$export")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[VolumeAttachment])

  /**
   * replace the specified CSIDriver
   * 
   * Expected answers:
   *   code 200 : CSIDriver (OK)
   *   code 201 : CSIDriver (Created)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSIDriver
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def replaceCSIDriver(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: CSIDriver)(implicit apiKey: ApiKeyValue): ApiRequestT[CSIDriver] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csidrivers/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSIDriver])

  /**
   * replace the specified CSINode
   * 
   * Expected answers:
   *   code 200 : CSINode (OK)
   *   code 201 : CSINode (Created)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the CSINode
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def replaceCSINode(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: CSINode)(implicit apiKey: ApiKeyValue): ApiRequestT[CSINode] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/apis/storage.k8s.io/v1beta1/csinodes/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[CSINode])

  /**
   * replace the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : StorageClass (OK)
   *   code 201 : StorageClass (Created)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def replaceStorageClass(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: StorageClass)(implicit apiKey: ApiKeyValue): ApiRequestT[StorageClass] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/apis/storage.k8s.io/v1beta1/storageclasses/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[StorageClass])

  /**
   * replace the specified VolumeAttachment
   * 
   * Expected answers:
   *   code 200 : VolumeAttachment (OK)
   *   code 201 : VolumeAttachment (Created)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the VolumeAttachment
   * @param pretty If 'true', then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param body 
   */
  def replaceVolumeAttachment(name: String, pretty: Option[String] = None, dryRun: Option[String] = None, fieldManager: Option[String] = None, body: VolumeAttachment)(implicit apiKey: ApiKeyValue): ApiRequestT[VolumeAttachment] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/apis/storage.k8s.io/v1beta1/volumeattachments/${name}?pretty=$pretty&dryRun=$dryRun&fieldManager=$fieldManager")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[VolumeAttachment])

}

