/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

/**
  * ContainerStatus contains details for the current status of this container.
  */
case class ContainerStatus(
    /* Container's ID in the format 'docker://<container_id>'. */
    containerID: Option[String] = None,
    /* The image the container is running. More info: https://kubernetes.io/docs/concepts/containers/images */
    image: String,
    /* ImageID of the container's image. */
    imageID: String,
    lastState: Option[ContainerState] = None,
    /* This must be a DNS_LABEL. Each container in a pod must have a unique name. Cannot be updated. */
    name: String,
    /* Specifies whether the container has passed its readiness probe. */
    ready: Boolean,
    /* The number of times the container has been restarted, currently based on the number of dead containers that have not yet been removed. Note that this is calculated from dead containers. But those containers are subject to garbage collection. This value will get capped at 5 by GC. */
    restartCount: Int,
    state: Option[ContainerState] = None)
  extends ApiModel
