/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * ContainerStateTerminated is a terminated state of a container.
   */
case class ContainerStateTerminated(
  /* Container's ID in the format 'docker://<container_id>' */
  containerID: Option[String] = None,
  /* Exit status from the last termination of the container */
  exitCode: Int,
  /* Time at which the container last terminated */
  finishedAt: Option[OffsetDateTime] = None,
  /* Message regarding the last termination of the container */
  message: Option[String] = None,
  /* (brief) reason from the last termination of the container */
  reason: Option[String] = None,
  /* Signal from the last termination of the container */
  signal: Option[Int] = None,
  /* Time at which previous execution of the container started */
  startedAt: Option[OffsetDateTime] = None
) extends ApiModel


