/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

/**
  * CronJobStatus represents the current state of a cron job.
  */
case class CronJobStatus(
    /* A list of pointers to currently running jobs. */
    active: Option[Seq[ObjectReference]] = None,
    /* Information when was the last time the job was successfully scheduled. */
    lastScheduleTime: Option[OffsetDateTime] = None)
  extends ApiModel
