/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class ExtensionsV1beta1SupplementalGroupsStrategyOptions (
  /* ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs. */
  ranges: Option[Seq[ExtensionsV1beta1IDRange]] = None,
  /* rule is the strategy that will dictate what supplemental groups is used in the SecurityContext. */
  rule: Option[String] = None
) extends ApiModel


