/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class ExtensionsV1beta1DeploymentStrategy (
  rollingUpdate: Option[ExtensionsV1beta1RollingUpdateDeployment] = None,
  /* Type of deployment. Can be \"Recreate\" or \"RollingUpdate\". Default is RollingUpdate. */
  `type`: Option[String] = None
) extends ApiModel


