/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * HorizontalPodAutoscalerCondition describes the state of a HorizontalPodAutoscaler at a certain point.
   */
case class HorizontalPodAutoscalerCondition(
  /* lastTransitionTime is the last time the condition transitioned from one status to another */
  lastTransitionTime: Option[OffsetDateTime] = None,
  /* message is a human-readable explanation containing details about the transition */
  message: Option[String] = None,
  /* reason is the reason for the condition's last transition. */
  reason: Option[String] = None,
  /* status is the status of the condition (True, False, Unknown) */
  status: String,
  /* type describes the current condition */
  `type`: String
) extends ApiModel


