/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * JobStatus represents the current state of a Job.
   */
case class JobStatus(
  /* The number of actively running pods. */
  active: Option[Int] = None,
  /* Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
  completionTime: Option[OffsetDateTime] = None,
  /* The latest available observations of an object's current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ */
  conditions: Option[Seq[JobCondition]] = None,
  /* The number of pods which reached phase Failed. */
  failed: Option[Int] = None,
  /* Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
  startTime: Option[OffsetDateTime] = None,
  /* The number of pods which reached phase Succeeded. */
  succeeded: Option[Int] = None
) extends ApiModel


