/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
   */
case class LimitRangeItem(
  /* Default resource requirement limit value by resource name if resource limit is omitted. */
  default: Option[Map[String, String]] = None,
  /* DefaultRequest is the default resource requirement request value by resource name if resource request is omitted. */
  defaultRequest: Option[Map[String, String]] = None,
  /* Max usage constraints on this kind by resource name. */
  max: Option[Map[String, String]] = None,
  /* MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource. */
  maxLimitRequestRatio: Option[Map[String, String]] = None,
  /* Min usage constraints on this kind by resource name. */
  min: Option[Map[String, String]] = None,
  /* Type of resource that this limit applies to. */
  `type`: Option[String] = None
) extends ApiModel


