/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

/**
  * PersistentVolumeClaimCondition contails details about state of pvc
  */
case class PersistentVolumeClaimCondition(
    /* Last time we probed the condition. */
    lastProbeTime: Option[OffsetDateTime] = None,
    /* Last time the condition transitioned from one status to another. */
    lastTransitionTime: Option[OffsetDateTime] = None,
    /* Human-readable message indicating details about last transition. */
    message: Option[String] = None,
    /* Unique, this should be a short, machine understandable string that gives the reason for condition's last transition. If it reports \"ResizeStarted\" that means the underlying persistent volume is being resized. */
    reason: Option[String] = None,
    status: String,
    `type`: String)
  extends ApiModel
