/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

/**
  * ReplicationControllerCondition describes the state of a replication controller at a certain point.
  */
case class ReplicationControllerCondition(
    /* The last time the condition transitioned from one status to another. */
    lastTransitionTime: Option[OffsetDateTime] = None,
    /* A human readable message indicating details about the transition. */
    message: Option[String] = None,
    /* The reason for the condition's last transition. */
    reason: Option[String] = None,
    /* Status of the condition, one of True, False, Unknown. */
    status: String,
    /* Type of replication controller condition. */
    `type`: String)
  extends ApiModel
