/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.
   */
case class ScopedResourceSelectorRequirement(
  /* Represents a scope's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. */
  operator: String,
  /* The name of the scope that the selector applies to. */
  scopeName: String,
  /* An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch. */
  values: Option[Seq[String]] = None
) extends ApiModel


