/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1Affinity (
  nodeAffinity: Option[V1NodeAffinity] = None,
  podAffinity: Option[V1PodAffinity] = None,
  podAntiAffinity: Option[V1PodAntiAffinity] = None
) extends ApiModel


