/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1APIResource (
  /* categories is a list of the grouped resources this resource belongs to (e.g. 'all') */
  categories: Option[Seq[String]] = None,
  /* group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale\". */
  group: Option[String] = None,
  /* kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo') */
  kind: String,
  /* name is the plural name of the resource. */
  name: String,
  /* namespaced indicates if a resource is namespaced or not. */
  namespaced: Boolean,
  /* shortNames is a list of suggested short names of the resource. */
  shortNames: Option[Seq[String]] = None,
  /* singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface. */
  singularName: String,
  /* The hash value of the storage version, the version this resource is converted to when written to the data store. Value must be treated as opaque by clients. Only equality comparison on the value is valid. This is an alpha feature and may change or be removed in the future. The field is populated by the apiserver only if the StorageVersionHash feature gate is enabled. This field will remain optional even if it graduates. */
  storageVersionHash: Option[String] = None,
  /* verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy) */
  verbs: Seq[String],
  /* version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)\". */
  version: Option[String] = None
) extends ApiModel


