/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1ConfigMapNodeConfigSource (
  /* KubeletConfigKey declares which key of the referenced ConfigMap corresponds to the KubeletConfiguration structure This field is required in all cases. */
  kubeletConfigKey: String,
  /* Name is the metadata.name of the referenced ConfigMap. This field is required in all cases. */
  name: String,
  /* Namespace is the metadata.namespace of the referenced ConfigMap. This field is required in all cases. */
  namespace: String,
  /* ResourceVersion is the metadata.ResourceVersion of the referenced ConfigMap. This field is forbidden in Node.Spec, and required in Node.Status. */
  resourceVersion: Option[String] = None,
  /* UID is the metadata.UID of the referenced ConfigMap. This field is forbidden in Node.Spec, and required in Node.Status. */
  uid: Option[String] = None
) extends ApiModel


