/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1DaemonSetStatus (
  /* Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision. */
  collisionCount: Option[Int] = None,
  /* Represents the latest available observations of a DaemonSet's current state. */
  conditions: Option[Seq[V1DaemonSetCondition]] = None,
  /* The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  currentNumberScheduled: Int,
  /* The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  desiredNumberScheduled: Int,
  /* The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds) */
  numberAvailable: Option[Int] = None,
  /* The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ */
  numberMisscheduled: Int,
  /* The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and ready. */
  numberReady: Int,
  /* The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds) */
  numberUnavailable: Option[Int] = None,
  /* The most recent generation observed by the daemon set controller. */
  observedGeneration: Option[Long] = None,
  /* The total number of nodes that are running updated daemon pod */
  updatedNumberScheduled: Option[Int] = None
) extends ApiModel


