/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import org.joda.time.DateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1EventSeries (
  /* Number of occurrences in this series up to the last heartbeat time */
  count: Option[Int] = None,
  /* Time of the last occurrence observed */
  lastObservedTime: Option[DateTime] = None,
  /* State of this Series: Ongoing or Finished Deprecated. Planned removal for 1.18 */
  state: Option[String] = None
) extends ApiModel


