/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import org.joda.time.DateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1Event (
  /* What action was taken/failed regarding to the Regarding object. */
  action: Option[String] = None,
  /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources */
  apiVersion: Option[String] = None,
  /* The number of times this event has occurred. */
  count: Option[Int] = None,
  /* Time when this Event was first observed. */
  eventTime: Option[DateTime] = None,
  /* The time at which the event was first recorded. (Time of server receipt is in TypeMeta.) */
  firstTimestamp: Option[DateTime] = None,
  involvedObject: V1ObjectReference,
  /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds */
  kind: Option[String] = None,
  /* The time at which the most recent occurrence of this event was recorded. */
  lastTimestamp: Option[DateTime] = None,
  /* A human-readable description of the status of this operation. */
  message: Option[String] = None,
  metadata: V1ObjectMeta,
  /* This should be a short, machine understandable string that gives the reason for the transition into the object's current status. */
  reason: Option[String] = None,
  related: Option[V1ObjectReference] = None,
  /* Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`. */
  reportingComponent: Option[String] = None,
  /* ID of the controller instance, e.g. `kubelet-xyzf`. */
  reportingInstance: Option[String] = None,
  series: Option[V1EventSeries] = None,
  source: Option[V1EventSource] = None,
  /* Type of this event (Normal, Warning), new types could be added in the future */
  `type`: Option[String] = None
) extends ApiModel


