/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1HorizontalPodAutoscalerSpec (
  /* upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas. */
  maxReplicas: Int,
  /* lower limit for the number of pods that can be set by the autoscaler, default 1. */
  minReplicas: Option[Int] = None,
  scaleTargetRef: V1CrossVersionObjectReference,
  /* target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified the default autoscaling policy will be used. */
  targetCPUUtilizationPercentage: Option[Int] = None
) extends ApiModel


