/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import org.joda.time.DateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1LeaseSpec (
  /* acquireTime is a time when the current lease was acquired. */
  acquireTime: Option[DateTime] = None,
  /* holderIdentity contains the identity of the holder of a current lease. */
  holderIdentity: Option[String] = None,
  /* leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measure against time of last observed RenewTime. */
  leaseDurationSeconds: Option[Int] = None,
  /* leaseTransitions is the number of transitions of a lease between holders. */
  leaseTransitions: Option[Int] = None,
  /* renewTime is a time when the current holder of a lease has last updated the lease. */
  renewTime: Option[DateTime] = None
) extends ApiModel


