/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.custom.Quantity
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1NodeStatus (
  /* List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses */
  addresses: Option[Seq[V1NodeAddress]] = None,
  /* Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity. */
  allocatable: Option[Map[String, Quantity]] = None,
  /* Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity */
  capacity: Option[Map[String, Quantity]] = None,
  /* Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/concepts/nodes/node/#condition */
  conditions: Option[Seq[V1NodeCondition]] = None,
  config: Option[V1NodeConfigStatus] = None,
  daemonEndpoints: Option[V1NodeDaemonEndpoints] = None,
  /* List of container images on this node */
  images: Option[Seq[V1ContainerImage]] = None,
  nodeInfo: Option[V1NodeSystemInfo] = None,
  /* NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated. */
  phase: Option[String] = None,
  /* List of volumes that are attached to the node. */
  volumesAttached: Option[Seq[V1AttachedVolume]] = None,
  /* List of attachable volumes in use (mounted) by the node. */
  volumesInUse: Option[Seq[String]] = None
) extends ApiModel


