/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1ResourceAttributes (
  /* Group is the API Group of the Resource.  \"*\" means all. */
  group: Option[String] = None,
  /* Name is the name of the resource being requested for a \"get\" or deleted for a \"delete\". \"\" (empty) means all. */
  name: Option[String] = None,
  /* Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces \"\" (empty) is defaulted for LocalSubjectAccessReviews \"\" (empty) is empty for cluster-scoped resources \"\" (empty) means \"all\" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview */
  namespace: Option[String] = None,
  /* Resource is one of the existing resource types.  \"*\" means all. */
  resource: Option[String] = None,
  /* Subresource is one of the existing resource types.  \"\" means none. */
  subresource: Option[String] = None,
  /* Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  \"*\" means all. */
  verb: Option[String] = None,
  /* Version is the API Version of the Resource.  \"*\" means all. */
  version: Option[String] = None
) extends ApiModel


