/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1ScaleIOPersistentVolumeSource (
  /* Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\" */
  fsType: Option[String] = None,
  /* The host address of the ScaleIO API Gateway. */
  gateway: String,
  /* The name of the ScaleIO Protection Domain for the configured storage. */
  protectionDomain: Option[String] = None,
  /* Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
  readOnly: Option[Boolean] = None,
  secretRef: V1SecretReference,
  /* Flag to enable/disable SSL communication with Gateway, default false */
  sslEnabled: Option[Boolean] = None,
  /* Indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned. */
  storageMode: Option[String] = None,
  /* The ScaleIO Storage Pool associated with the protection domain. */
  storagePool: Option[String] = None,
  /* The name of the storage system as configured in ScaleIO. */
  system: String,
  /* The name of a volume already created in the ScaleIO system that is associated with this volume source. */
  volumeName: Option[String] = None
) extends ApiModel


