/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1SecretReference (
  /* Name is unique within a namespace to reference a secret resource. */
  name: Option[String] = None,
  /* Namespace defines the space within which the secret name must be unique. */
  namespace: Option[String] = None
) extends ApiModel


