/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import org.joda.time.DateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1Taint (
  /* Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute. */
  effect: String,
  /* Required. The taint key to be applied to a node. */
  key: String,
  /* TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints. */
  timeAdded: Option[DateTime] = None,
  /* Required. The taint value corresponding to the taint key. */
  value: Option[String] = None
) extends ApiModel


