/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V1VolumeMount (
  /* Path within the container at which the volume should be mounted.  Must not contain ':'. */
  mountPath: String,
  /* mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10. */
  mountPropagation: Option[String] = None,
  /* This must match the Name of a Volume. */
  name: String,
  /* Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. */
  readOnly: Option[Boolean] = None,
  /* Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root). */
  subPath: Option[String] = None,
  /* Expanded path within the volume from which the container's volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment. Defaults to \"\" (volume's root). SubPathExpr and SubPath are mutually exclusive. This field is beta in 1.15. */
  subPathExpr: Option[String] = None
) extends ApiModel


