/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import org.joda.time.DateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

case class V2beta2HorizontalPodAutoscalerCondition (
  /* lastTransitionTime is the last time the condition transitioned from one status to another */
  lastTransitionTime: Option[DateTime] = None,
  /* message is a human-readable explanation containing details about the transition */
  message: Option[String] = None,
  /* reason is the reason for the condition's last transition. */
  reason: Option[String] = None,
  /* status is the status of the condition (True, False, Unknown) */
  status: String,
  /* type describes the current condition */
  `type`: String
) extends ApiModel


