/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * Volume represents a named volume in a pod that may be accessed by any container in the pod.
   */
case class Volume(
  awsElasticBlockStore: Option[AWSElasticBlockStoreVolumeSource] = None,
  azureDisk: Option[AzureDiskVolumeSource] = None,
  azureFile: Option[AzureFileVolumeSource] = None,
  cephfs: Option[CephFSVolumeSource] = None,
  cinder: Option[CinderVolumeSource] = None,
  configMap: Option[ConfigMapVolumeSource] = None,
  csi: Option[CSIVolumeSource] = None,
  downwardAPI: Option[DownwardAPIVolumeSource] = None,
  emptyDir: Option[EmptyDirVolumeSource] = None,
  fc: Option[FCVolumeSource] = None,
  flexVolume: Option[FlexVolumeSource] = None,
  flocker: Option[FlockerVolumeSource] = None,
  gcePersistentDisk: Option[GCEPersistentDiskVolumeSource] = None,
  gitRepo: Option[GitRepoVolumeSource] = None,
  glusterfs: Option[GlusterfsVolumeSource] = None,
  hostPath: Option[HostPathVolumeSource] = None,
  iscsi: Option[ISCSIVolumeSource] = None,
  /* Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
  name: String,
  nfs: Option[NFSVolumeSource] = None,
  persistentVolumeClaim: Option[PersistentVolumeClaimVolumeSource] = None,
  photonPersistentDisk: Option[PhotonPersistentDiskVolumeSource] = None,
  portworxVolume: Option[PortworxVolumeSource] = None,
  projected: Option[ProjectedVolumeSource] = None,
  quobyte: Option[QuobyteVolumeSource] = None,
  rbd: Option[RBDVolumeSource] = None,
  scaleIO: Option[ScaleIOVolumeSource] = None,
  secret: Option[SecretVolumeSource] = None,
  storageos: Option[StorageOSVolumeSource] = None,
  vsphereVolume: Option[VsphereVirtualDiskVolumeSource] = None
) extends ApiModel


