/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

/**
  * Projection that may be projected along with other supported volume types
  */
case class VolumeProjection(
    configMap: Option[ConfigMapProjection] = None,
    downwardAPI: Option[DownwardAPIProjection] = None,
    secret: Option[SecretProjection] = None,
    serviceAccountToken: Option[ServiceAccountTokenProjection] = None)
  extends ApiModel
