/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * volumeDevice describes a mapping of a raw block device within a container.
   */
case class VolumeDevice(
  /* devicePath is the path inside of the container that the device will be mapped to. */
  devicePath: String,
  /* name must match the name of a persistentVolumeClaim in the pod */
  name: String
) extends ApiModel


