/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.api

import com.virtuslab.kubernetes.client.openapi.model.V1APIResourceList
import com.virtuslab.kubernetes.client.openapi.model.V1TokenReview
import com.virtuslab.kubernetes.client.openapi.core._
import com.virtuslab.kubernetes.client.openapi.core.CollectionFormats._
import com.virtuslab.kubernetes.client.openapi.core.ApiKeyLocations._

object AuthenticationV1Api {

  def apply(baseUrl: String = "http://localhost") = new AuthenticationV1Api(baseUrl)
}

class AuthenticationV1Api(baseUrl: String) {
  
  /**
   * create a TokenReview
   * 
   * Expected answers:
   *   code 200 : V1TokenReview (OK)
   *   code 201 : V1TokenReview (Created)
   *   code 202 : V1TokenReview (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
   * @param pretty If 'true', then the output is pretty printed.
   * @param body 
   */
  def createTokenReview(dryRun: Option[String] = None, fieldManager: Option[String] = None, pretty: Option[String] = None, body: V1TokenReview)(implicit apiKey: ApiKeyValue
): ApiRequest[V1TokenReview] =
    ApiRequest[V1TokenReview](ApiMethods.POST, baseUrl, "/apis/authentication.k8s.io/v1/tokenreviews", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withBody(body)
      .withQueryParam("dryRun", dryRun)
      .withQueryParam("fieldManager", fieldManager)
      .withQueryParam("pretty", pretty)
      .withSuccessResponse[V1TokenReview](200)
      .withErrorResponse[V1TokenReview](201)
      .withErrorResponse[V1TokenReview](202)
      .withErrorResponse[Unit](401)
      

  /**
   * get available resources
   * 
   * Expected answers:
   *   code 200 : V1APIResourceList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def getAPIResources()(implicit apiKey: ApiKeyValue
): ApiRequest[V1APIResourceList] =
    ApiRequest[V1APIResourceList](ApiMethods.GET, baseUrl, "/apis/authentication.k8s.io/v1/", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withSuccessResponse[V1APIResourceList](200)
      .withErrorResponse[Unit](401)
      



}

