/**
  * Kubernetes
  * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: v1.15.10
  *
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package com.virtuslab.kubernetes.client.openapi.api

import com.virtuslab.kubernetes.client.openapi.model.APIResourceList
import com.virtuslab.kubernetes.client.openapi.model.LocalSubjectAccessReview
import com.virtuslab.kubernetes.client.openapi.model.SelfSubjectAccessReview
import com.virtuslab.kubernetes.client.openapi.model.SelfSubjectRulesReview
import com.virtuslab.kubernetes.client.openapi.model.SubjectAccessReview
import com.virtuslab.kubernetes.client.openapi.core._
import alias._
import sttp.client._
import sttp.model.Method

object AuthorizationV1beta1Api {

  def apply(baseUrl: String = "http://localhost")(implicit serializer: SttpSerializer) = new AuthorizationV1beta1Api(baseUrl)
}

class AuthorizationV1beta1Api(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
    * create a LocalSubjectAccessReview
    *
    * Expected answers:
    *   code 200 : LocalSubjectAccessReview (OK)
    *   code 201 : LocalSubjectAccessReview (Created)
    *   code 202 : LocalSubjectAccessReview (Accepted)
    *   code 401 :  (Unauthorized)
    *
    * Available security schemes:
    *   BearerToken (apiKey)
    *
    * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
    * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
    * @param namespace object name and auth scope, such as for teams and projects
    * @param pretty If 'true', then the output is pretty printed.
    * @param body
    */
  def createNamespacedLocalSubjectAccessReview(
      dryRun: Option[String] = None,
      fieldManager: Option[String] = None,
      namespace: String,
      pretty: Option[String] = None,
      body: LocalSubjectAccessReview
    )(implicit
      apiKey: ApiKeyValue
    ): ApiRequestT[LocalSubjectAccessReview] =
    basicRequest
      .method(
        Method.POST,
        uri"$baseUrl/apis/authorization.k8s.io/v1beta1/namespaces/${namespace}/localsubjectaccessreviews?dryRun=$dryRun&fieldManager=$fieldManager&pretty=$pretty"
      )
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[LocalSubjectAccessReview])

  /**
    * create a SelfSubjectAccessReview
    *
    * Expected answers:
    *   code 200 : SelfSubjectAccessReview (OK)
    *   code 201 : SelfSubjectAccessReview (Created)
    *   code 202 : SelfSubjectAccessReview (Accepted)
    *   code 401 :  (Unauthorized)
    *
    * Available security schemes:
    *   BearerToken (apiKey)
    *
    * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
    * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
    * @param pretty If 'true', then the output is pretty printed.
    * @param body
    */
  def createSelfSubjectAccessReview(
      dryRun: Option[String] = None,
      fieldManager: Option[String] = None,
      pretty: Option[String] = None,
      body: SelfSubjectAccessReview
    )(implicit
      apiKey: ApiKeyValue
    ): ApiRequestT[SelfSubjectAccessReview] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/authorization.k8s.io/v1beta1/selfsubjectaccessreviews?dryRun=$dryRun&fieldManager=$fieldManager&pretty=$pretty")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[SelfSubjectAccessReview])

  /**
    * create a SelfSubjectRulesReview
    *
    * Expected answers:
    *   code 200 : SelfSubjectRulesReview (OK)
    *   code 201 : SelfSubjectRulesReview (Created)
    *   code 202 : SelfSubjectRulesReview (Accepted)
    *   code 401 :  (Unauthorized)
    *
    * Available security schemes:
    *   BearerToken (apiKey)
    *
    * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
    * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
    * @param pretty If 'true', then the output is pretty printed.
    * @param body
    */
  def createSelfSubjectRulesReview(
      dryRun: Option[String] = None,
      fieldManager: Option[String] = None,
      pretty: Option[String] = None,
      body: SelfSubjectRulesReview
    )(implicit
      apiKey: ApiKeyValue
    ): ApiRequestT[SelfSubjectRulesReview] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/authorization.k8s.io/v1beta1/selfsubjectrulesreviews?dryRun=$dryRun&fieldManager=$fieldManager&pretty=$pretty")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[SelfSubjectRulesReview])

  /**
    * create a SubjectAccessReview
    *
    * Expected answers:
    *   code 200 : SubjectAccessReview (OK)
    *   code 201 : SubjectAccessReview (Created)
    *   code 202 : SubjectAccessReview (Accepted)
    *   code 401 :  (Unauthorized)
    *
    * Available security schemes:
    *   BearerToken (apiKey)
    *
    * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
    * @param fieldManager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
    * @param pretty If 'true', then the output is pretty printed.
    * @param body
    */
  def createSubjectAccessReview(
      dryRun: Option[String] = None,
      fieldManager: Option[String] = None,
      pretty: Option[String] = None,
      body: SubjectAccessReview
    )(implicit
      apiKey: ApiKeyValue
    ): ApiRequestT[SubjectAccessReview] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/apis/authorization.k8s.io/v1beta1/subjectaccessreviews?dryRun=$dryRun&fieldManager=$fieldManager&pretty=$pretty")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .body(body)
      .response(asJson[SubjectAccessReview])

  /**
    * get available resources
    *
    * Expected answers:
    *   code 200 : APIResourceList (OK)
    *   code 401 :  (Unauthorized)
    *
    * Available security schemes:
    *   BearerToken (apiKey)
    */
  def getAPIResources()(implicit apiKey: ApiKeyValue): ApiRequestT[APIResourceList] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/apis/authorization.k8s.io/v1beta1/")
      .contentType("application/json")
      .header("authorization", apiKey.value)
      .response(asJson[APIResourceList])

}
