/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.api

import com.virtuslab.kubernetes.client.openapi.core._
import com.virtuslab.kubernetes.client.openapi.core.CollectionFormats._
import com.virtuslab.kubernetes.client.openapi.core.ApiKeyLocations._

object LogsApi {

  def apply(baseUrl: String = "http://localhost") = new LogsApi(baseUrl)
}

class LogsApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param logpath path to the log
   */
  def logFileHandler(logpath: String)(implicit apiKey: ApiKeyValue
): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, baseUrl, "/logs/{logpath}", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withPathParam("logpath", logpath)
      .withErrorResponse[Unit](401)
      

  /**
   * Expected answers:
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def logFileListHandler()(implicit apiKey: ApiKeyValue
): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, baseUrl, "/logs/", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withErrorResponse[Unit](401)
      



}

