/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.virtuslab.kubernetes.client.openapi.api

import com.virtuslab.kubernetes.client.openapi.model.VersionInfo
import com.virtuslab.kubernetes.client.openapi.core._
import com.virtuslab.kubernetes.client.openapi.core.CollectionFormats._
import com.virtuslab.kubernetes.client.openapi.core.ApiKeyLocations._

object VersionApi {

  def apply(baseUrl: String = "http://localhost") = new VersionApi(baseUrl)
}

class VersionApi(baseUrl: String) {
  
  /**
   * get the code version
   * 
   * Expected answers:
   *   code 200 : VersionInfo (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def getCode()(implicit apiKey: ApiKeyValue
): ApiRequest[VersionInfo] =
    ApiRequest[VersionInfo](ApiMethods.GET, baseUrl, "/version/", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withSuccessResponse[VersionInfo](200)
      .withErrorResponse[Unit](401)
      



}

