/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * APIServiceStatus contains derived information about an API server
   */
case class APIServiceStatus(
  /* Current service state of apiService. */
  conditions: Option[Seq[APIServiceCondition]] = None
) extends ApiModel


