/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

  /**
   * APIServiceCondition describes the state of an APIService at a particular point
   */
case class APIServiceCondition(
  /* Last time the condition transitioned from one status to another. */
  lastTransitionTime: Option[OffsetDateTime] = None,
  /* Human-readable message indicating details about last transition. */
  message: Option[String] = None,
  /* Unique, one-word, CamelCase reason for the condition's last transition. */
  reason: Option[String] = None,
  /* Status is the status of the condition. Can be True, False, Unknown. */
  status: String,
  /* Type is the type of the condition. */
  `type`: String
) extends ApiModel


