/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class CertificateSigningRequestCondition(
  /* timestamp for the last update to this condition */
  lastUpdateTime: Option[OffsetDateTime] = None,
  /* human readable message with details about the request state */
  message: Option[String] = None,
  /* brief reason for the request state */
  reason: Option[String] = None,
  /* request approval state, currently Approved or Denied. */
  `type`: String
) extends ApiModel


