/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * Information about the condition of a component.
   */
case class ComponentCondition(
  /* Condition error code for a component. For example, a health check error code. */
  error: Option[String] = None,
  /* Message about the condition for a component. For example, information about a health check. */
  message: Option[String] = None,
  /* Status of the condition for a component. Valid values for \"Healthy\": \"True\", \"False\", or \"Unknown\". */
  status: String,
  /* Type of condition for a component. Valid value: \"Healthy\" */
  `type`: String
) extends ApiModel


