/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * ContainerStateRunning is a running state of a container.
   */
case class ContainerStateRunning(
  /* Time at which the container was last (re-)started */
  startedAt: Option[OffsetDateTime] = None
) extends ApiModel


