/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * ContainerStateWaiting is a waiting state of a container.
   */
case class ContainerStateWaiting(
  /* Message regarding why the container is not yet running. */
  message: Option[String] = None,
  /* (brief) reason the container is not yet running. */
  reason: Option[String] = None
) extends ApiModel


