/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
   */
case class CustomResourceDefinitionStatus(
  acceptedNames: CustomResourceDefinitionNames,
  /* Conditions indicate state for particular aspects of a CustomResourceDefinition */
  conditions: Seq[CustomResourceDefinitionCondition],
  /* StoredVersions are all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so the migration controller can first finish a migration to another version (i.e. that no old objects are left in the storage), and then remove the rest of the versions from this list. None of the versions in this list can be removed from the spec.Versions field. */
  storedVersions: Seq[String]
) extends ApiModel


