/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
   */
case class DaemonSetUpdateStrategy(
  rollingUpdate: Option[RollingUpdateDaemonSet] = None,
  /* Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate. */
  `type`: Option[String] = None
) extends ApiModel


