/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * EnvVarSource represents a source for the value of an EnvVar.
   */
case class EnvVarSource(
  configMapKeyRef: Option[ConfigMapKeySelector] = None,
  fieldRef: Option[ObjectFieldSelector] = None,
  resourceFieldRef: Option[ResourceFieldSelector] = None,
  secretKeyRef: Option[SecretKeySelector] = None
) extends ApiModel


