/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

  /**
   * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
   */
case class EventSeries(
  /* Number of occurrences in this series up to the last heartbeat time */
  count: Int,
  /* Time when last Event from the series was seen before last heartbeat. */
  lastObservedTime: OffsetDateTime,
  /* Information whether this series is ongoing or finished. Deprecated. Planned removal for 1.18 */
  state: String
) extends ApiModel


