/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * Info contains versioning information. how we'll want to distribute that information.
   */
case class Info(
  buildDate: String,
  compiler: String,
  gitCommit: String,
  gitTreeState: String,
  gitVersion: String,
  goVersion: String,
  major: String,
  minor: String,
  platform: String
) extends ApiModel


