/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
   */
case class LoadBalancerIngress(
  /* Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers) */
  hostname: Option[String] = None,
  /* IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers) */
  ip: Option[String] = None
) extends ApiModel


