/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * MetricStatus describes the last-read state of a single metric.
   */
case class MetricStatus(
  external: Option[ExternalMetricStatus] = None,
  `object`: Option[ObjectMetricStatus] = None,
  pods: Option[PodsMetricStatus] = None,
  resource: Option[ResourceMetricStatus] = None,
  /* type is the type of metric source.  It will be one of \"Object\", \"Pods\" or \"Resource\", each corresponds to a matching field in the object. */
  `type`: String
) extends ApiModel


