/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
   */
case class NodeSelectorTerm(
  /* A list of node selector requirements by node's labels. */
  matchExpressions: Option[Seq[NodeSelectorRequirement]] = None,
  /* A list of node selector requirements by node's fields. */
  matchFields: Option[Seq[NodeSelectorRequirement]] = None
) extends ApiModel


