/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * PersistentVolumeClaimStatus is the current status of a persistent volume claim.
   */
case class PersistentVolumeClaimStatus(
  /* AccessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
  accessModes: Option[Seq[String]] = None,
  /* Represents the actual resources of the underlying volume. */
  capacity: Option[Map[String, String]] = None,
  /* Current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to 'ResizeStarted'. */
  conditions: Option[Seq[PersistentVolumeClaimCondition]] = None,
  /* Phase represents the current phase of PersistentVolumeClaim. */
  phase: Option[String] = None
) extends ApiModel


