/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * ReplicaSetStatus represents the current status of a ReplicaSet.
   */
case class ReplicaSetStatus(
  /* The number of available replicas (ready for at least minReadySeconds) for this replica set. */
  availableReplicas: Option[Int] = None,
  /* Represents the latest available observations of a replica set's current state. */
  conditions: Option[Seq[ReplicaSetCondition]] = None,
  /* The number of pods that have labels matching the labels of the pod template of the replicaset. */
  fullyLabeledReplicas: Option[Int] = None,
  /* ObservedGeneration reflects the generation of the most recently observed ReplicaSet. */
  observedGeneration: Option[Long] = None,
  /* The number of ready replicas for this replica set. */
  readyReplicas: Option[Int] = None,
  /* Replicas is the most recently oberved number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller */
  replicas: Int
) extends ApiModel


