/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
   */
case class ResourceQuotaSpec(
  /* hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/ */
  hard: Option[Map[String, String]] = None,
  scopeSelector: Option[ScopeSelector] = None,
  /* A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects. */
  scopes: Option[Seq[String]] = None
) extends ApiModel


