/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

  /**
   * RoleRef contains information that points to the role being used
   */
case class RoleRef(
  /* APIGroup is the group for the resource being referenced */
  apiGroup: String,
  /* Kind is the type of resource being referenced */
  kind: String,
  /* Name is the name of resource being referenced */
  name: String
) extends ApiModel


