/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

  /**
   * VolumeError captures an error encountered during a volume operation.
   */
case class VolumeError(
  /* String detailing the error encountered during Attach or Detach operation. This string may be logged, so it should not contain sensitive information. */
  message: Option[String] = None,
  /* Time the error was encountered. */
  time: Option[OffsetDateTime] = None
) extends ApiModel


