/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.virtuslab.kubernetes.client.openapi.core.ApiModel

  /**
   * Represents a vSphere volume resource.
   */
case class VsphereVirtualDiskVolumeSource(
  /* Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
  fsType: Option[String] = None,
  /* Storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName. */
  storagePolicyID: Option[String] = None,
  /* Storage Policy Based Management (SPBM) profile name. */
  storagePolicyName: Option[String] = None,
  /* Path that identifies vSphere volume vmdk */
  volumePath: String
) extends ApiModel


